[2023-12-25T12:52:04.905+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: producer_dag.produce_task manual__2023-12-25T12:52:03.697539+00:00 [queued]>
[2023-12-25T12:52:04.912+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: producer_dag.produce_task manual__2023-12-25T12:52:03.697539+00:00 [queued]>
[2023-12-25T12:52:04.912+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-12-25T12:52:04.922+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): produce_task> on 2023-12-25 12:52:03.697539+00:00
[2023-12-25T12:52:04.926+0000] {standard_task_runner.py:57} INFO - Started process 5784 to run task
[2023-12-25T12:52:04.929+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'producer_dag', 'produce_task', 'manual__2023-12-25T12:52:03.697539+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/producer.py', '--cfg-path', '/tmp/tmplyonzrn2']
[2023-12-25T12:52:04.931+0000] {standard_task_runner.py:85} INFO - Job 61: Subtask produce_task
[2023-12-25T12:52:04.975+0000] {task_command.py:410} INFO - Running <TaskInstance: producer_dag.produce_task manual__2023-12-25T12:52:03.697539+00:00 [running]> on host c56b1de7f6cf
[2023-12-25T12:52:05.039+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='producer_dag' AIRFLOW_CTX_TASK_ID='produce_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-25T12:52:03.697539+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-25T12:52:03.697539+00:00'
[2023-12-25T12:52:05.051+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/producer.py", line 69, in produce
    new_data, new_ntu_data, scaler = ti.xcom_pull(task_ids='generate_random_data_task')
TypeError: cannot unpack non-iterable NoneType object
[2023-12-25T12:52:05.057+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=producer_dag, task_id=produce_task, execution_date=20231225T125203, start_date=20231225T125204, end_date=20231225T125205
[2023-12-25T12:52:05.068+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 61 for task produce_task (cannot unpack non-iterable NoneType object; 5784)
[2023-12-25T12:52:05.101+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-12-25T12:52:05.117+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
