[2023-12-25T10:19:28.015+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: producer_dag.check_kafka_topic_task manual__2023-12-25T10:19:07.622915+00:00 [queued]>
[2023-12-25T10:19:28.066+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: producer_dag.check_kafka_topic_task manual__2023-12-25T10:19:07.622915+00:00 [queued]>
[2023-12-25T10:19:28.066+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-12-25T10:19:28.146+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): check_kafka_topic_task> on 2023-12-25 10:19:07.622915+00:00
[2023-12-25T10:19:28.196+0000] {standard_task_runner.py:57} INFO - Started process 2495 to run task
[2023-12-25T10:19:28.215+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'producer_dag', 'check_kafka_topic_task', 'manual__2023-12-25T10:19:07.622915+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/producer.py', '--cfg-path', '/tmp/tmpq9k6606i']
[2023-12-25T10:19:28.226+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask check_kafka_topic_task
[2023-12-25T10:19:28.466+0000] {task_command.py:410} INFO - Running <TaskInstance: producer_dag.check_kafka_topic_task manual__2023-12-25T10:19:07.622915+00:00 [running]> on host 0fa599bd5d59
[2023-12-25T10:19:28.947+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='producer_dag' AIRFLOW_CTX_TASK_ID='check_kafka_topic_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-25T10:19:07.622915+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-25T10:19:07.622915+00:00'
[2023-12-25T10:19:28.956+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/producer.py", line 124, in check_and_print_kafka_topic_exists
    admin_client = AdminClient(**kafka_conf)
TypeError: __init__() got an unexpected keyword argument 'bootstrap.servers'
[2023-12-25T10:19:29.016+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=producer_dag, task_id=check_kafka_topic_task, execution_date=20231225T101907, start_date=20231225T101928, end_date=20231225T101929
[2023-12-25T10:19:29.146+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 51 for task check_kafka_topic_task (__init__() got an unexpected keyword argument 'bootstrap.servers'; 2495)
[2023-12-25T10:19:29.205+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-12-25T10:19:29.296+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
