[2023-12-25T13:50:29.318+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: consumer_dag.insert_task manual__2023-12-25T13:50:27.038146+00:00 [queued]>
[2023-12-25T13:50:29.324+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: consumer_dag.insert_task manual__2023-12-25T13:50:27.038146+00:00 [queued]>
[2023-12-25T13:50:29.324+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-12-25T13:50:29.334+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): insert_task> on 2023-12-25 13:50:27.038146+00:00
[2023-12-25T13:50:29.338+0000] {standard_task_runner.py:57} INFO - Started process 9622 to run task
[2023-12-25T13:50:29.340+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'consumer_dag', 'insert_task', 'manual__2023-12-25T13:50:27.038146+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/consumer.py', '--cfg-path', '/tmp/tmpmdd3i_xy']
[2023-12-25T13:50:29.340+0000] {standard_task_runner.py:85} INFO - Job 177: Subtask insert_task
[2023-12-25T13:50:29.369+0000] {task_command.py:410} INFO - Running <TaskInstance: consumer_dag.insert_task manual__2023-12-25T13:50:27.038146+00:00 [running]> on host c56b1de7f6cf
[2023-12-25T13:50:29.424+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='consumer_dag' AIRFLOW_CTX_TASK_ID='insert_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-25T13:50:27.038146+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-25T13:50:27.038146+00:00'
[2023-12-25T13:50:29.431+0000] {logging_mixin.py:150} INFO - <class 'list'>
[2023-12-25T13:50:29.431+0000] {logging_mixin.py:150} INFO - [4.94289, 7.34265, 7.19271, 373.23972000000003, 47.02401, 2230.80795]
[2023-12-25T13:50:29.438+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/consumer.py", line 68, in insert_to_db
    cursor.execute(insert_query, (current_time, new_data[0][0], new_data[0][1], new_data[0][2], new_data[0][3], new_data[0][4], new_data[0][5]))
TypeError: 'float' object is not subscriptable
[2023-12-25T13:50:29.443+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=consumer_dag, task_id=insert_task, execution_date=20231225T135027, start_date=20231225T135029, end_date=20231225T135029
[2023-12-25T13:50:29.452+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 177 for task insert_task ('float' object is not subscriptable; 9622)
[2023-12-25T13:50:29.472+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-12-25T13:50:29.483+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
